export const brawlers = [
    {
        id: "1",
        nome: "Shelly",
        classe: "destruidor",
        raridade: "inicial",
        vida: 7800,
        velocidadeMovimento: "rápida",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2017,
        quebraParedes: true,
    },
    {
        id: "2",
        nome: "Nita",
        classe: "destruidor",
        raridade: "Raro",
        vida: 8400,
        velocidadeMovimento: "normal",
        alcance: "normal",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2017,
        quebraParedes: false,
    },
    {
        id: "3",
        nome: "Colt",
        classe: "destruidor",
        raridade: "raro",
        vida: 6200,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2017,
        quebraParedes: true,
    },
    {
        id: "4",
        nome: "Bull",
        classe: "Tanque",
        raridade: "raro",
        vida: 10600,
        velocidadeMovimento: "rápida",
        alcance: "normal",
        velocidadeRecarga: "normal",
        anoLancamento: 2017,
        quebraParedes: true,
    },
    {
        id: "5",
        nome: "Brock",
        classe: "tiro preciso",
        raridade: "raro",
        vida: 6000,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2017,
        quebraParedes: true,
    },
    {
        id: "6",
        nome: "El Primo",
        classe: "tanque",
        raridade: "raro",
        vida: 13000,
        velocidadeMovimento: "rápida",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2017,
        quebraParedes: true,
    },
    {
        id: "7",
        nome: "Barley",
        classe: "detonador",
        raridade: "raro",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2017,
        quebraParedes: false,
    },
    {
        id: "8",
        nome: "Poco",
        classe: "suporte",
        raridade: "raro",
        vida: 8000,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2017,
        quebraParedes: false,
    },
    {
        id: "9",
        nome: "Rosa",
        classe: "tanque",
        raridade: "raro",
        vida: 10800,
        velocidadeMovimento: "rápida",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2019,
        quebraParedes: false,
    },
    {
        id: "10",
        nome: "Jessie",
        classe: "controle",
        raridade: "super-raro",
        vida: 6600,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2017,
        quebraParedes: false,
    },

    {
        id: "11",
        nome: "Dynamike",
        classe: "detonador",
        raridade: "super-raro",
        vida: 6000,
        velocidadeMovimento: "rápida",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2017,
        quebraParedes: true,
    },
    {
        id: "12",
        nome: "Tick",
        classe: "detonador",
        raridade: "super-raro",
        vida: 4800,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "muito lenta",
        anoLancamento: 2019,
        quebraParedes: true,
    },
    {
        id: "13",
        nome: "8-Bit",
        classe: "destruidor",
        raridade: "super-raro",
        vida: 11111111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "muito lenta",
        alcance: "muito longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2019,
        quebraParedes: false,
    },
    {
        id: "14",
        nome: "Rico",
        classe: "destruidor",
        raridade: "super-raro",
        vida: 6000,
        velocidadeMovimento: "normal",
        alcance: "muito longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2018,
        quebraParedes: false,
    },
    {
        id: "15",
        nome: "Darryl",
        classe: "tanque",
        raridade: "super-raro",
        vida: 11000,
        velocidadeMovimento: "rápida",
        alcance: "normal",
        velocidadeRecarga: "normal",
        anoLancamento: 2017,
        quebraParedes: false,
    },
    {
        id: "16",
        nome: "Penny",
        classe: "controle",
        raridade: "super-raro",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2018,
        quebraParedes: false,
    },
    {
        id: "17",
        nome: "Carl",
        classe: "destruidor",
        raridade: "super-raro",
        vida: 8400,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2019,
        quebraParedes: false,
    },
    {
        id: "18",
        nome: "Jacky",
        classe: "tanque",
        raridade: "super-raro",
        vida: 111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "rápida",
        alcance: "curto",
        velocidadeRecarga: "normal",
        anoLancamento: 2020,
        quebraParedes: false,
    },
    {
        id: "19",
        nome: "Gus",
        classe: "suporte",
        raridade: "super-raro",
        vida: 6600,
        velocidadeMovimento: "normal",
        alcance: "muito longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2022,
        quebraParedes: false,
    },
    {
        id: "20",
        nome: "Bo",
        classe: "controle",
        raridade: "épico",
        vida: 7600,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2017,
        quebraParedes: true,
    },

    {
        id: "21",
        nome: "Emz",
        classe: "controle",
        raridade: "épico",
        vida: 7800,
        velocidadeMovimento: "normal",
        alcance: "normal",
        velocidadeRecarga: "lenta",
        anoLancamento: 2019,
        quebraParedes: false,
    },
    {
        id: "22",
        nome: "Stu",
        classe: "algoz",
        raridade: "épico",
        vida: 6800,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2021,
        quebraParedes: true,
    },
    {
        id: "23",
        nome: "Piper",
        classe: "tiro preciso",
        raridade: "épico",
        vida: 5000,
        velocidadeMovimento: "normal",
        alcance: "muito longo",
        velocidadeRecarga: "muito lenta",
        anoLancamento: 2017,
        quebraParedes: true,
    },
    {
        id: "24",
        nome: "Pam",
        classe: "suporte",
        raridade: "épico",
        vida: 10000,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2017,
        quebraParedes: false,
    },
    {
        id: "25",
        nome: "Frank",
        classe: "tanque",
        raridade: "épico",
        vida: 14000,
        velocidadeMovimento: "rápida",
        alcance: "normal",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2018,
        quebraParedes: true,
    },
    {
        id: "26",
        nome: "Bibi",
        classe: "tanque",
        raridade: "épico",
        vida: 10000,
        velocidadeMovimento: "muito rápida",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2019,
        quebraParedes: false,
    },
    {
        id: "27",
        nome: "Bea",
        classe: "tiro preciso",
        raridade: "épico",
        vida: 5600,
        velocidadeMovimento: "normal",
        alcance: "muito longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2019,
        quebraParedes: false,
    },
    {
        id: "28",
        nome: "Nani",
        classe: "tiro preciso",
        raridade: "épico",
        vida: 5000,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2020,
        quebraParedes: true,
    },
    {
        id: "29",
        nome: "Edgar",
        classe: "algoz",
        raridade: "épico",
        vida: 7400,
        velocidadeMovimento: "muito rápida",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2020,
        quebraParedes: false,
    },
    {
        id: "30",
        nome: "Griff",
        classe: "controle",
        raridade: "épico",
        vida: 7400,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2021,
        quebraParedes: true,
    },

    {
        id: "31",
        nome: "Grom",
        classe: "detornador",
        raridade: "épico",
        vida: 6000,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2021,
        quebraParedes: true,
    },
    {
        id: "32",
        nome: "Bonnie",
        classe: "tiro preciso",
        raridade: "épico",
        vida: 10000,
        velocidadeMovimento: "lenta",
        alcance: "longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2022,
        quebraParedes: false,
    },
    {
        id: "33",
        nome: "Gale",
        classe: "controle",
        raridade: "épico",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2020,
        quebraParedes: false,
    },
    {
        id: "34",
        nome: "Colette",
        classe: "destruidor",
        raridade: "épico",
        vida: 7200,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2020,
        quebraParedes: false,
    },
    {
        id: "35",
        nome: "Belle",
        classe: "tiro preciso",
        raridade: "épico",
        vida: 5600,
        velocidadeMovimento: "normal",
        alcance: "muito longo",
        velocidadeRecarga: "rápida",
        anoLancamento: 2021,
        quebraParedes: false,
    },
    {
        id: "36",
        nome: "Ash",
        classe: "tanque",
        raridade: "épico",
        vida: 11800,
        velocidadeMovimento: "normal",
        alcance: "normal",
        velocidadeRecarga: "rápida",
        anoLancamento: 2021,
        quebraParedes: false,
    },
    {
        id: "37",
        nome: "Lola",
        classe: "destruidor",
        raridade: "épico",
        vida: 8000,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2021,
        quebraParedes: false,
    },
    {
        id: "38",
        nome: "Sam",
        classe: "algoz",
        raridade: "épico",
        vida: 11400,
        velocidadeMovimento: "rápida",
        alcance: "curto",
        velocidadeRecarga: "normal",
        anoLancamento: 2022,
        quebraParedes: false,
    },
    {
        id: "39",
        nome: "Mandy",
        classe: "tiro preciso",
        raridade: "épico",
        vida: 111111111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2023,
        quebraParedes: false,
    },
    {
        id: "40",
        nome: "Maisie",
        classe: "tiro preciso",
        raridade: "épico",
        vida: 8000,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2023,
        quebraParedes: false,
    },

    {
        id: "41",
        nome: "Hank",
        classe: "tanque",
        raridade: "épico",
        vida: 10400,
        velocidadeMovimento: "normal",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2023,
        quebraParedes: false,
    },
    {
        id: "42",
        nome: "Pearl",
        classe: "destruidor",
        raridade: "épico",
        vida: 8600,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2023,
        quebraParedes: true,
    },
    {
        id: "43",
        nome: "Larry e Lawrie",
        classe: "detonador",
        raridade: "épico",
        vida: 6000,
        velocidadeMovimento: "rápida",
        alcance: "longo",
        velocidadeRecarga: "muito lenta",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "44",
        nome: "Angelo",
        classe: "tiro preciso",
        raridade: "épico",
        vida: 6200,
        velocidadeMovimento: "muito rápida",
        alcance: "muito longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "45",
        nome: "Berry",
        classe: "detonador",
        raridade: "épico",
        vida: 5200,
        velocidadeMovimento: "normal",
        alcance: "normal",
        velocidadeRecarga: "muito lenta",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "46",
        nome: "Shade",
        classe: "algoz",
        raridade: "épico",
        vida: 7400,
        velocidadeMovimento: "muito rápida",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "47",
        nome: "Meeple",
        classe: "controle",
        raridade: "épico",
        vida: 6600,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2025,
        quebraParedes: false,
    },
    {
        id: "48",
        nome: "Trunk",
        classe: "tanque",
        raridade: "épico",
        vida: 10400,
        velocidadeMovimento: "rápida",
        alcance: "curto",
        velocidadeRecarga: "normal",
        anoLancamento: 2025,
        quebraParedes: false,
    },
    {
        id: "49",
        nome: "Mortis",
        classe: "algoz",
        raridade: "mítico",
        vida: 8000,
        velocidadeMovimento: "muito rápida",
        alcance: "curto",
        velocidadeRecarga: "muito lenta",
        anoLancamento: 2017,
        quebraParedes: false,
    },
    {
        id: "50",
        nome: "Tara",
        classe: "destruidor",
        raridade: "mítico",
        vida: 6600,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2017,
        quebraParedes: true,
    },

    {
        id: "51",
        nome: "Eugênio",
        classe: "controle",
        raridade: "mítico",
        vida: 7600,
        velocidadeMovimento: "normal",
        alcance: "muito longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2019,
        quebraParedes: true,
    },
    {
        id: "52",
        nome: "Max",
        classe: "suporte",
        raridade: "mítico",
        vida: 7000,
        velocidadeMovimento: "muito rápida",
        alcance: "longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2019,
        quebraParedes: false,
    },
    {
        id: "53",
        nome: "Mister P",
        classe: "controle",
        raridade: "mítico",
        vida: 7400,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2020,
        quebraParedes: false,
    },
    {
        id: "54",
        nome: "Sprout",
        classe: "detonador",
        raridade: "mítico",
        vida: 6400,
        velocidadeMovimento: "normal",
        alcance: "normal",
        velocidadeRecarga: "normal",
        anoLancamento: 2020,
        quebraParedes: false,
    },
    {
        id: "55",
        nome: "Byron",
        classe: "suporte",
        raridade: "mítico",
        vida: 5200,
        velocidadeMovimento: "normal",
        alcance: "muito longo",
        velocidadeRecarga: "rápida",
        anoLancamento: 2020,
        quebraParedes: false,
    },
    {
        id: "56",
        nome: "Squeak",
        classe: "controle",
        raridade: "mítico",
        vida: 7600,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2021,
        quebraParedes: false,
    },
    {
        id: "57",
        nome: "Lou",
        classe: "controle",
        raridade: "mítico",
        vida: 6800,
        velocidadeMovimento: "normal",
        alcance: "muito longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2020,
        quebraParedes: false,
    },
    {
        id: "58",
        nome: "Ruffs",
        classe: "suporte",
        raridade: "mítico",
        vida: 6000,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "rápida",
        anoLancamento: 2021,
        quebraParedes: true,
    },
    {
        id: "59",
        nome: "Buzz",
        classe: "algoz",
        raridade: "mítico",
        vida: 10000,
        velocidadeMovimento: "rápida",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 111111111111111111111111111111111111111111111111111111,
        quebraParedes: false,
    },
    {
        id: "60",
        nome: "Fang",
        classe: "algoz",
        raridade: "mítico",
        vida: 9000,
        velocidadeMovimento: "rápida",
        alcance: "muito longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2022,
        quebraParedes: false,
    },

    {
        id: "61",
        nome: "Eve",
        classe: "destruidor",
        raridade: "mítico",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "normal",
        alcance: "muito longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2022,
        quebraParedes: false,
    },
    {
        id: "62",
        nome: "Janet",
        classe: "tiro preciso",
        raridade: "mítico",
        vida: 6800,
        velocidadeMovimento: "normal",
        alcance: "normal",
        velocidadeRecarga: "normal",
        anoLancamento: 2022,
        quebraParedes: false,
    },
    {
        id: "63",
        nome: "Otis",
        classe: "controle",
        raridade: "mítico",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2022,
        quebraParedes: false,
    },
    {
        id: "64",
        nome: "Buster",
        classe: "tanque",
        raridade: "mítico",
        vida: 10000,
        velocidadeMovimento: "rápida",
        alcance: "normal",
        velocidadeRecarga: "normal",
        anoLancamento: 2022,
        quebraParedes: false,
    },
    {
        id: "65",
        nome: "Gray",
        classe: "suporte",
        raridade: "mítico",
        vida: 6800,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "rápida",
        anoLancamento: 2022,
        quebraParedes: true,
    },
    {
        id: "66",
        nome: "R-T",
        classe: "destruidor",
        raridade: "mítico",
        vida: 8200,
        velocidadeMovimento: "normal",
        alcance: "muito longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2023,
        quebraParedes: false,
    },
    {
        id: "67",
        nome: "Willow",
        classe: "controle",
        raridade: "mítico",
        vida: 6600,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2023,
        quebraParedes: false,
    },
    {
        id: "68",
        nome: "Doug",
        classe: "suporte",
        raridade: "mítico",
        vida: 10400,
        velocidadeMovimento: "rápida",
        alcance: "curto",
        velocidadeRecarga: "normal",
        anoLancamento: 2023,
        quebraParedes: false,
    },
    {
        id: "69",
        nome: "Chuck",
        classe: "controle",
        raridade: "mítico",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "rápida",
        alcance: "normal",
        velocidadeRecarga: "lenta",
        anoLancamento: 2023,
        quebraParedes: false,
    },
    {
        id: "70",
        nome: "Charlie",
        classe: "controle",
        raridade: "mítico",
        vida: 7400,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2023,
        quebraParedes: false,
    },

    {
        id: "71",
        nome: "Mico",
        classe: "algoz",
        raridade: "mítico",
        vida: 7000,
        velocidadeMovimento: "muito rápida",
        alcance: "normal",
        velocidadeRecarga: "muito lenta",
        anoLancamento: 2023,
        quebraParedes: false,
    },
    {
        id: "72",
        nome: "Melodie",
        classe: "algoz",
        raridade: "mítico",
        vida: 7600,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "73",
        nome: "Lily",
        classe: "algoz",
        raridade: "mítico",
        vida: 8400,
        velocidadeMovimento: "muito rápida",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "74",
        nome: "Clancy",
        classe: "destruidor",
        raridade: "mítico",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "75",
        nome: "Moe",
        classe: "destruidor",
        raridade: "mítico",
        vida: 7200,
        velocidadeMovimento: "rápida",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "76",
        nome: "Juju",
        classe: "detonador",
        raridade: "mítico",
        vida: 6200,
        velocidadeMovimento: "normal",
        alcance: "normal",
        velocidadeRecarga: "normal",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "77",
        nome: "Ollie",
        classe: "tanque",
        raridade: "mítico",
        vida: 10800,
        velocidadeMovimento: "rápida",
        alcance: "normal",
        velocidadeRecarga: "normal",
        anoLancamento: 2025,
        quebraParedes: false,
    },
    {
        id: "78",
        nome: "Lumi",
        classe: "destruidor",
        raridade: "mítico",
        vida: 5800,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2025,
        quebraParedes: false,
    },
    {
        id: "79",
        nome: "Finx",
        classe: "controle",
        raridade: "mítico",
        vida: 7400,
        velocidadeMovimento: "rápida",
        alcance: "longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2025,
        quebraParedes: false,
    },
    {
        id: "80",
        nome: "Jae-Yong",
        classe: "suporte",
        raridade: "mítico",
        vida: 7000,
        velocidadeMovimento: "rápida",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2025,
        quebraParedes: false,
    },

    {
        id: "81",
        nome: "Alli",
        classe: "algoz",
        raridade: "mítico",
        vida: 7800,
        velocidadeMovimento: "rápida",
        alcance: "curto",
        velocidadeRecarga: "lenta",
        anoLancamento: 2025,
        quebraParedes: false,
    },
    {
        id: "82",
        nome: "Mina",
        classe: "destruidor",
        raridade: "mítico",
        vida: 7200,
        velocidadeMovimento: "rápida",
        alcance: "longo",
        velocidadeRecarga: "rápida",
        anoLancamento: 2025,
        quebraParedes: false,
    },
    {
        id: "83",
        nome: "Ziggy",
        classe: "controle",
        raridade: "mítico",
        vida: 6000,
        velocidadeMovimento: "rápida",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2025,
        quebraParedes: false,
    },
    {
        id: "84",
        nome: "Gigi",
        classe: "algoz",
        raridade: "mítico",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "muito rápida",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2025,
        quebraParedes: false,
    },
    {
        id: "85",
        nome: "Glowbert",
        classe: "suporte",
        raridade: "mítico",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "rápida",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2026,
        quebraParedes: false,
    },
    {
        id: "86",
        nome: "Spike",
        classe: "destruidor",
        raridade: "lendário",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "lenta",
        anoLancamento: 2017,
        quebraParedes: false,
    },
    {
        id: "87",
        nome: "Corvo",
        classe: "algoz",
        raridade: "lendário",
        vida: 6000,
        velocidadeMovimento: "muito rápida",
        alcance: "longo",
        velocidadeRecarga: "rápida",
        anoLancamento: 2017,
        quebraParedes: false,
    },
    {
        id: "88",
        nome: "Leon",
        classe: "algoz",
        raridade: "lendário",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "muito rápida",
        alcance: "muito longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2018,
        quebraParedes: false,
    },
    {
        id: "89",
        nome: "Sandy",
        classe: "controle",
        raridade: "lendário",
        vida: 8200,
        velocidadeMovimento: "rápida",
        alcance: "normal",
        velocidadeRecarga: "normal",
        anoLancamento: 2019,
        quebraParedes: false,
    },
    {
        id: "90",
        nome: "Amber",
        classe: "controle",
        raridade: "lendário",
        vida: 1111111111111111111111111111111111111111111111111111111111111111111,
        velocidadeMovimento: "normal",
        alcance: "longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2020,
        quebraParedes: false,
    },

    {
        id: "91",
        nome: "Meg",
        classe: "tanque",
        raridade: "lendário",
        vida: 4800,
        velocidadeMovimento: "muito rápida",
        alcance: "longo",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2021,
        quebraParedes: false,
    },
    {
        id: "92",
        nome: "Wattson",
        classe: "destruidor",
        raridade: "lendário",
        vida: 6600,
        velocidadeMovimento: "lenta",
        alcance: "normal",
        velocidadeRecarga: "lenta",
        anoLancamento: 2020,
        quebraParedes: false,
    },
    {
        id: "93",
        nome: "Chester",
        classe: "destruidor",
        raridade: "lendário",
        vida: 7400,
        velocidadeMovimento: "rápida",
        alcance: "longo",
        velocidadeRecarga: "normal",
        anoLancamento: 2022,
        quebraParedes: true,
    },
    {
        id: "94",
        nome: "Cordelius",
        classe: "algoz",
        raridade: "lendário",
        vida: 7000,
        velocidadeMovimento: "muito rápida",
        alcance: "normal",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2023,
        quebraParedes: false,
    },
    {
        id: "95",
        nome: "Kit",
        classe: "suporte",
        raridade: "lendário",
        vida: 6200,
        velocidadeMovimento: "muito rápida",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "96",
        nome: "Draco",
        classe: "tanque",
        raridade: "lendário",
        vida: 11200,
        velocidadeMovimento: "normal",
        alcance: "normal",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "97",
        nome: "Kenji",
        classe: "algoz",
        raridade: "lendário",
        vida: 8000,
        velocidadeMovimento: "muito rápida",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2024,
        quebraParedes: false,
    },
    {
        id: "98",
        nome: "Pierce",
        classe: "tiro preciso",
        raridade: "lendário",
        vida: 6000,
        velocidadeMovimento: "normal",
        alcance: "muito longo",
        velocidadeRecarga: "muito lenta",
        anoLancamento: 2025,
        quebraParedes: false,
    },
    {
        id: "99",
        nome: "Kaze",
        classe: "algoz",
        raridade: "ultralendário",
        vida: 8200,
        velocidadeMovimento: "muito rápida",
        alcance: "curto",
        velocidadeRecarga: "muito rápida",
        anoLancamento: 2025,
        quebraParedes: false,
    },
];